package othi.thg.client.pathFinding;

/**
 * A path from one point to another generated by the path finding code
 * 
 * @author Kevin Glass
 * @author Dong Won Kim
 */
import othi.thg.client.THGClientDefault;

public class Path {
        private static final long serialVersionUID = 20070812112327L;     
	/** The path coordinates */
	private Step[] path = new Step [THGClientDefault.PATH_SEARCH_DEPTH];
	/** The size of the path */
	private int size;
	
	/**
	 * Create a new empty path
	 */
	public Path() {
	}
	
        /**
         * 
         * @param x The x coordinate of the point
         * @param y The y coordinate of the point
         * Written by Dong Won Kim on March 8,2008
         */
        public void appendStep(int x, int y) {
            path[size] = new Step(x,y);
            size++;
        }
        
        /**
         * 
         * @param index The index of the point to retrieve
         * @return The step information, the position on the map
         * Written by Dong Won Kim on March 8,2008
         */
        Path.Step getStep(int index) {
            Step step = path[index];
            if (step != null) return step;
            else return null;
        }
                
	/**
	 * Get the X coordinate of the point at the specified index
	 * 
	 * @param index The index of the point to retrieve 
	 * @return The x coordinate of the point at the specified index
         * Modified by Dong Won Kim on March 8,2008
	 */
	public int getX(int index) {
            return path[index].getX();
	}

	/**
	 * Get the Y coordinate of the point at the specified index
	 * 
	 * @param index The index of the point to retrieve 
	 * @return The y coordinate of the point at the specified index
         * Modified by Dong Won Kim on March 8,2008
	 */
	public int getY(int index) {
		return path[index].getY();
	}
	
	/**
	 * Get the size/length of the path
	 * 
	 * @return The size of the path
	 */
	public int getSize() {
		return size;
	}
        
        //Written by Dong Won Kim on March 8, 2008        
        private class Step {
            private static final long serialVersionUID = 1L;
        
            private int x;
            private int y;
            
            private Step(int x, int y) {
                this.x = x;
                this.y = y;
            }
            
            private int getX(){
                return x;
            }
            
            private int getY(){
                return y;
            }            
        }
}
